let token=localStorage.getItem('mad_admin_token')||'';let products=[];let orders=[];const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{'Content-Type':'application/json','x-admin-token':token,...(opts.headers||{})}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Error');return d}
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
async function login(){token=$('#token').value.trim();try{await api('/api/admin/products');localStorage.setItem('mad_admin_token',token);$('#loginBox').hidden=true;$('#dashboard').hidden=false;await loadAll()}catch(e){$('#loginError').textContent='رمز الإدارة غير صحيح'}}
async function loadAll(){[products,orders]=await Promise.all([api('/api/admin/products'),api('/api/admin/orders')]);renderStats();renderProducts();renderOrders()}
function renderStats(){const total=orders.filter(o=>o.payment_status==='paid').reduce((s,o)=>s+Number(o.total||0),0);$('#ordersCount').textContent=orders.length;$('#salesTotal').textContent=`${total.toFixed(2)} ر.س`;$('#productsCount').textContent=products.length;$('#newCount').textContent=orders.filter(o=>o.status==='new').length}
function renderOrders(){const statuses={awaiting_payment:'بانتظار الدفع',payment_failed:'فشل الدفع',new:'جديد',processing:'قيد التجهيز',shipped:'تم الشحن',completed:'مكتمل',cancelled:'ملغي'};$('#ordersBody').innerHTML=orders.length?orders.map(o=>`<tr><td>${o.id}</td><td>${o.customer.name}</td><td>${o.customer.phone}</td><td>${o.customer.city}</td><td>${o.total} ر.س</td><td><select class="status" data-order="${o.id}">${Object.entries(statuses).map(([v,n])=>`<option value="${v}" ${o.status===v?'selected':''}>${n}</option>`).join('')}</select></td><td>${new Date(o.created_at||o.createdAt).toLocaleString('ar-SA')}</td></tr>`).join(''):'<tr><td colspan="7">لا توجد طلبات بعد.</td></tr>';$$('[data-order]').forEach(s=>s.onchange=async()=>{await api('/api/admin/orders/'+s.dataset.order,{method:'PUT',body:JSON.stringify({status:s.value})});toast('تم تحديث الحالة');orders=await api('/api/admin/orders');renderStats()})}
function renderProducts(){$('#productsBody').innerHTML=products.map(p=>`<tr><td>${p.id}</td><td>${p.icon||'📦'} ${p.ar}<br><small>${p.en}</small></td><td>${p.category}</td><td>${p.price}</td><td>${p.stock}</td><td>${p.active===false?'لا':'نعم'}</td><td><button class="action edit" data-edit="${p.id}">تعديل</button><button class="action danger" data-delete="${p.id}">حذف</button></td></tr>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>editProduct(+b.dataset.edit));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteProduct(+b.dataset.delete))}
function openTab(name){$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));['orders','products','add'].forEach(n=>$('#'+n+'Panel').hidden=n!==name)}
function editProduct(id){const p=products.find(x=>x.id===id),f=$('#productForm');Object.entries(p).forEach(([k,v])=>{if(f.elements[k]){if(f.elements[k].type==='checkbox')f.elements[k].checked=v!==false;else f.elements[k].value=v??''}});$('#formTitle').textContent='تعديل المنتج';openTab('add')}
async function deleteProduct(id){if(!confirm('حذف المنتج؟'))return;await api('/api/admin/products/'+id,{method:'DELETE'});products=await api('/api/admin/products');renderProducts();renderStats();toast('تم الحذف')}
$('#productForm').onsubmit=async e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f).entries());d.active=f.elements.active.checked;const file=$('#imageFile').files[0];if(file){if(file.size>4*1024*1024)throw new Error('حجم الصورة أكبر من 4MB');const dataUrl=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)});const uploaded=await api('/api/admin/upload',{method:'POST',body:JSON.stringify({dataUrl})});d.image=uploaded.url;}const id=d.id;delete d.id;try{if(id)await api('/api/admin/products/'+id,{method:'PUT',body:JSON.stringify(d)});else await api('/api/admin/products',{method:'POST',body:JSON.stringify(d)});f.reset();f.elements.active.checked=true;$('#formTitle').textContent='إضافة منتج';products=await api('/api/admin/products');renderProducts();renderStats();openTab('products');toast('تم حفظ المنتج')}catch(e){toast(e.message)}}
$('#loginBtn').onclick=login;$('#token').onkeydown=e=>{if(e.key==='Enter')login()};$('#logout').onclick=()=>{localStorage.removeItem('mad_admin_token');location.reload()};$$('.tabs button').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));$('#refreshOrders').onclick=async()=>{orders=await api('/api/admin/orders');renderOrders();renderStats()};$('#refreshProducts').onclick=async()=>{products=await api('/api/admin/products');renderProducts();renderStats()};$('#cancelEdit').onclick=()=>{$('#productForm').reset();$('#formTitle').textContent='إضافة منتج';openTab('products')};if(token){$('#loginBox').hidden=true;$('#dashboard').hidden=false;loadAll().catch(()=>{localStorage.removeItem('mad_admin_token');location.reload()})}

$('#imageFile').onchange=e=>{const f=e.target.files[0];if(f)$('#imagePreview').innerHTML=`<img src="${URL.createObjectURL(f)}" style="max-width:180px;border-radius:12px">`};
